# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
include: package:flutter_lints/flutter.yaml

analyzer:
# Structural settings can go here if needed in the future

linter:
  # The lint rules applied to this project can be customized in the section below.
  rules:
    # Avoid lint crashes when running tests inside the primary application directory
    depend_on_referenced_packages: false
    invalid_use_of_visible_for_testing_member: false

    # Optional configurations (Uncomment if needed matching style preferences)
    # avoid_print: false
    # prefer_single_quotes: true
