name: e_comm
description: "Enterprise White-Label Multi-Tenant E-commerce Engine."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Core Presentation State Management
  provider: ^6.1.2

  # Service Locator Dependency Injection Engine
  get_it: ^9.2.1

  # High-Performance HTTP Networking Client
  dio: ^5.7.0

  # Functional Programming Core Utilities for Type-Safe Failure Monads
  fpdart: ^1.1.0

  # Deep Structural Object Value Comparison to Eliminate Frame Rendering Triggers
  equatable: ^2.0.5

  # Native Platform Icons Styling Base
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Quality Automation Standard Rules
  flutter_lints: ^5.0.0

  # Automated Compilation Testing Mocks Generators
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
